import { Platform, StyleSheet } from "react-native";

const monoFont = Platform.select({ ios: "Menlo", default: "monospace" });

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: "#F1F5F9" },
  header: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 16,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  eyebrow: {
    color: "#0EA5E9",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.7,
    marginBottom: 2,
  },
  title: {
    color: "#0F172A",
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.7,
  },
  headerStatus: {
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    borderRadius: 20,
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerStatusOnline: { backgroundColor: "#ECFDF5" },
  statusDot: {
    backgroundColor: "#94A3B8",
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusDotOnline: { backgroundColor: "#10B981" },
  headerStatusText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "700",
  },
  tabs: {
    backgroundColor: "#E2E8F0",
    borderRadius: 12,
    flexDirection: "row",
    gap: 3,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 4,
  },
  tab: {
    alignItems: "center",
    borderRadius: 9,
    flex: 1,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 7,
  },
  tabActive: {
    backgroundColor: "#0F172A",
    elevation: 3,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.16,
    shadowRadius: 4,
  },
  tabLabel: { color: "#64748B", fontSize: 12, fontWeight: "700" },
  tabLabelActive: { color: "#F8FAFC" },
  pressed: { opacity: 0.72 },
  content: { gap: 14, padding: 16, paddingBottom: 36 },
  sectionIntro: { alignItems: "center", flexDirection: "row", gap: 12 },
  sectionIcon: {
    alignItems: "center",
    backgroundColor: "#E0F2FE",
    borderRadius: 12,
    height: 46,
    justifyContent: "center",
    width: 46,
  },
  sectionIntroText: { flex: 1 },
  sectionTitle: { color: "#0F172A", fontSize: 18, fontWeight: "800" },
  sectionDescription: {
    color: "#64748B",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    elevation: 2,
    padding: 16,
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  cardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardTitle: { color: "#0F172A", fontSize: 15, fontWeight: "800" },
  cardCaption: {
    color: "#94A3B8",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  refreshButton: {
    alignItems: "center",
    backgroundColor: "#F0F9FF",
    borderRadius: 9,
    flexDirection: "row",
    gap: 5,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  refreshButtonText: {
    color: "#0284C7",
    fontSize: 12,
    fontWeight: "800",
  },
  emptyState: {
    alignItems: "center",
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  emptyStateTitle: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 8,
  },
  emptyStateText: {
    color: "#94A3B8",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
    textAlign: "center",
  },
  deviceList: { gap: 8, marginTop: 16 },
  deviceRow: {
    alignItems: "center",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    padding: 12,
  },
  deviceRowSelected: {
    backgroundColor: "#F0F9FF",
    borderColor: "#7DD3FC",
  },
  deviceIcon: {
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  deviceIconSelected: { backgroundColor: "#E0F2FE" },
  deviceDetails: { flex: 1, marginHorizontal: 11 },
  deviceName: { color: "#1E293B", fontSize: 14, fontWeight: "700" },
  deviceAddress: { color: "#94A3B8", fontSize: 11, marginTop: 3 },
  profileRow: { flexDirection: "row", gap: 8, marginTop: 14 },
  profileButton: {
    alignItems: "center",
    borderColor: "#CBD5E1",
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 44,
  },
  profileButtonSelected: {
    backgroundColor: "#F0F9FF",
    borderColor: "#7DD3FC",
  },
  profileButtonText: { color: "#475569", fontSize: 13, fontWeight: "700" },
  profileButtonTextSelected: { color: "#0369A1" },
  profileHint: {
    color: "#64748B",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  connectedBadge: {
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    borderRadius: 12,
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  connectedBadgeDot: {
    backgroundColor: "#10B981",
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  connectedBadgeText: {
    color: "#047857",
    fontSize: 10,
    fontWeight: "800",
  },
  infoBanner: {
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    padding: 12,
  },
  infoBannerText: {
    color: "#475569",
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#0284C7",
    borderRadius: 12,
    flexDirection: "row",
    gap: 9,
    justifyContent: "center",
    minHeight: 50,
    paddingHorizontal: 18,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  buttonDisabled: { opacity: 0.45 },
  actionRow: { flexDirection: "row", gap: 10 },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#CBD5E1",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 48,
  },
  secondaryButtonText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "800",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 48,
  },
  dangerButtonText: {
    color: "#DC2626",
    fontSize: 13,
    fontWeight: "800",
  },
  formGroup: { marginTop: 16 },
  label: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 7,
  },
  inputShell: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  input: {
    color: "#0F172A",
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  formRow: { flexDirection: "row", gap: 10 },
  formRowPort: { flex: 0.72 },
  formRowMountpoint: { flex: 1.28 },
  switchRow: {
    alignItems: "center",
    borderTopColor: "#E2E8F0",
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 18,
    paddingTop: 16,
  },
  switchCopy: { flex: 1, paddingRight: 12 },
  switchTitle: { color: "#334155", fontSize: 13, fontWeight: "700" },
  switchDescription: {
    color: "#94A3B8",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  debugContent: { gap: 12, padding: 16, paddingBottom: 36 },
  debugDeviceBar: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 11,
  },
  debugDeviceInfo: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
  },
  connectionIndicator: {
    backgroundColor: "#94A3B8",
    borderRadius: 5,
    height: 10,
    marginRight: 10,
    width: 10,
  },
  connectionIndicatorOnline: { backgroundColor: "#10B981" },
  debugDeviceCopy: { flex: 1 },
  debugDeviceLabel: {
    color: "#94A3B8",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
  },
  debugDeviceName: {
    color: "#1E293B",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  compactButton: {
    backgroundColor: "#E0F2FE",
    borderRadius: 8,
    marginLeft: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  compactButtonText: {
    color: "#0369A1",
    fontSize: 11,
    fontWeight: "800",
  },
  selectDevicePrompt: {
    alignItems: "center",
    backgroundColor: "#F0F9FF",
    borderRadius: 10,
    flexDirection: "row",
    gap: 8,
    padding: 11,
  },
  selectDevicePromptText: {
    color: "#0369A1",
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
  },
  consoleCard: {
    backgroundColor: "#09111F",
    borderColor: "#1E293B",
    borderRadius: 14,
    borderWidth: 1,
    height: 320,
    overflow: "hidden",
  },
  consoleHeader: {
    alignItems: "center",
    backgroundColor: "#111C2D",
    borderBottomColor: "#253247",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  consoleTitleRow: { alignItems: "center", flexDirection: "row", gap: 7 },
  consoleLiveDot: {
    backgroundColor: "#64748B",
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  consoleLiveDotActive: { backgroundColor: "#22C55E" },
  consoleTitle: {
    color: "#CBD5E1",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  clearButtonText: { color: "#38BDF8", fontSize: 11, fontWeight: "700" },
  clearButtonDisabled: { color: "#475569" },
  consoleBody: { flexGrow: 1, padding: 13 },
  consoleLine: {
    alignItems: "flex-start",
    flexDirection: "row",
    marginBottom: 7,
  },
  consoleTime: {
    color: "#475569",
    fontFamily: monoFont,
    fontSize: 10,
    marginRight: 9,
    paddingTop: 1,
  },
  consoleMessage: {
    color: "#A7F3D0",
    flex: 1,
    fontFamily: monoFont,
    fontSize: 11,
    lineHeight: 16,
  },
  consoleEmpty: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    minHeight: 180,
    padding: 24,
  },
  consolePrompt: {
    color: "#38BDF8",
    fontFamily: monoFont,
    fontSize: 24,
    fontWeight: "700",
  },
  consoleEmptyTitle: {
    color: "#CBD5E1",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 10,
  },
  consoleEmptyText: {
    color: "#64748B",
    fontSize: 11,
    lineHeight: 17,
    marginTop: 4,
    textAlign: "center",
  },
  consoleFooter: { flexDirection: "row", justifyContent: "space-between" },
  consoleFooterText: { color: "#94A3B8", fontSize: 10 },
});
